# Generated by Django 4.2.2 on 2023-07-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('first_name', models.CharField(default='unknow', max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
