# Generated by Django 4.2.2 on 2023-07-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='unknow', max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
