# Generated by Django 4.2.2 on 2023-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opr', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
